### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by jsrpy** [ohjho/recommendation_system#1]
+1 for Surprise SVD.

Btw, I think you should note the dataset origin instead

[http://www2.informatik.uni-freiburg.de/~cziegler/BX/](http://www2.informatik.uni-freiburg.de/~cziegler/BX/)

**Comment by ohjho** [comment]
Thanks for the recommendation @jsrpy . We just decided to included it in the repo mainly for ease of use. And the files are within the Github limit of 100mb so I thought everyone's okay with that. 

I have added a reference to them for clarity 👍
